name: build-and-lint
on: 
  push: 
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install backend dependencies
        working-directory: Server
        run: npm ci

      - name: Lint backend
        working-directory: Server
        run: npm run lint

      - name: Install frontend dependencies
        working-directory: Client
        run: npm ci

      - name: Lint frontend
        working-directory: Client
        run: npm run lint
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
